# Matrizes

In [1]:
import numpy as np

In [2]:
matriz = np.array([[2, 3, 1], 
                   [4, 5, 7]])

In [3]:
matriz

array([[2, 3, 1],
       [4, 5, 7]])

In [5]:
matriz.shape

(2, 3)

In [6]:
matriz[0]

array([2, 3, 1])

In [7]:
matriz[0][1]

3

In [9]:
for i in range(matriz.shape[0]):
    print(matriz[i])
    for j in range(matriz.shape[1]):
        print(matriz[i][j])

[2 3 1]
2
3
1
[4 5 7]
4
5
7
